<a href="https://colab.research.google.com/github/RRAJ644/NLP/blob/main/Python_practice_25_07_2025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello World!")

Hello World


In [ ]:
# Variables
a=10 #int
b=10.5 #float
c = True #boolean
print(a)
print(b)
print(c)

10
10.5
True


In [ ]:
# Type casting
x = str(3)    # x will be '3'
y = int(3)    # y will be 3
z = float(3)  # z will be 3.0

print(x)
print(y)
print(z)


print(type(x))
print(type(y))
print(type(z))

3
3
3.0
<class 'str'>
<class 'int'>
<class 'float'>


In [ ]:
# Loops
fruits = ["apple", "banana", "cherry"]
for x in fruits:
  if x == "banana":
    continue #skips the element
  print(x)

apple
cherry


In [ ]:
# USER INPUT AND PRINT TABLE
number = eval(input("Enter your number: "))
for i in range(1,11):
  print(number * i)



Enter your number: 4
4
8
12
16
20
24
28
32
36
40


In [ ]:
# Print even number

x=1
while(x<10):
  if(x%2==0):
    print(x)
  x+=1

2
4
6
8


In [ ]:
# Count the number of vowels in a string
testString = "hello"
vowelCount = 0

vowels = 'aeiouAEIOU'

for i in testString:
  if i in vowels:
    vowelCount+=1

print(vowelCount)

2


In [ ]:
# Check if a string is a palindrome
testCase="NitiN"
i=0
j=len(testString)-1

isPalidrome=True

while(i<j):
  if(testCase[i]!=testCase[j]):
    isPalidrome = False
    break
  i+=1
  j-=1


if(isPalidrome):
  print("Palindrome")
else:
  print("Not Palindrome")


Palindrome


In [ ]:
lists = [1,2,3,4,5,6,7,8]

odds = []
evens = []

for i in lists:
  if(i %2 !=0):
    odds.append(i)
  if(i%2==0):
    evens.append(i)

print(odds)
print(evens)


print(lists)

[1, 3, 5, 7]
[2, 4, 6, 8]
[1, 2, 3, 4, 5, 6, 7, 8]


In [9]:
import numpy as np
a = np.array ([[1,2,3],[4,5,6],[6,7,8]])

print(a)
print(a.shape)
print(a.ndim)
print(a.dtype)

b = np.ones(2)
print(b)

c = np.zeros(2)
print(c)

d = np.arange(4)
print(d)

e = np.arange(2, 9, 2)
print(e)



[[1 2 3]
 [4 5 6]
 [6 7 8]]
(3, 3)
2
int64
[1. 1.]
[0. 0.]
[0 1 2 3]
[2 4 6 8]
